"""Generate the Hyprland push-to-talk keybind file for a chosen key.

The app cannot grab keys globally on Wayland, so push-to-talk relies on a
Hyprland keybind that signals this process (SIGUSR1 on press, SIGUSR2 on
release). This module renders that bind file for whatever key the user picks
in the GUI.
"""

MODIFIER_KEYSYMS = frozenset({
    "Alt_L", "Alt_R", "Control_L", "Control_R",
    "Shift_L", "Shift_R", "Super_L", "Super_R",
    "Meta_L", "Meta_R", "ISO_Level3_Shift",
})


def is_modifier(keysym: str) -> bool:
    return keysym in MODIFIER_KEYSYMS


def build_hypr_conf(keysym: str, pid_path: str) -> str:
    """Render the hyprland-ptt.conf contents binding *keysym* for push-to-talk."""
    flags = "n" if is_modifier(keysym) else ""
    mod_note = ""
    if is_modifier(keysym):
        mod_note = (
            "#\n"
            "# WARNING: this is a modifier key. On Hyprland a bare modifier fires the\n"
            "# press but usually NOT the release, so the recording never finalizes.\n"
            "# Pick a normal key (function key, Insert, Menu, …) for reliable behavior.\n"
        )
    return (
        '# Push-to-talk ("рация") for Machine Agent — GENERATED by the app.\n'
        f"# Bound key: {keysym}. Re-assign or reset it from the app window.\n"
        "#\n"
        "# This file must be sourced from your Hyprland config (then `hyprctl reload`):\n"
        "#     source = ~/projects/machine-agent/config/hyprland-ptt.conf\n"
        "#\n"
        "# SIGUSR1 = key pressed  -> start recording\n"
        "# SIGUSR2 = key released -> stop + transcribe + type at the cursor\n"
        f"{mod_note}"
        "\n"
        f'bind{flags}  = , {keysym}, exec, kill -USR1 "$(cat {pid_path} 2>/dev/null)"\n'
        f'bindr{flags} = , {keysym}, exec, kill -USR2 "$(cat {pid_path} 2>/dev/null)"\n'
    )
